// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	. "github.com/Batyr2024/todoGolang/domain"
)

type Querier interface {
	ChangeCheckedAll(ctx context.Context, arg *ChangeCheckedAllParams) ([]int32, error)
	ChangeCheckedByID(ctx context.Context, arg *ChangeCheckedByIDParams) (*Task, error)
	ChangeTextByID(ctx context.Context, arg *ChangeTextByIDParams) (*Task, error)
	Create(ctx context.Context, arg *CreateParams) (*Task, error)
	DeleteAll(ctx context.Context) ([]int32,error)
	DeleteByID(ctx context.Context, arg *DeleteByIDParams) (*Task, error)
	GetAll(ctx context.Context) ([]*Task, error)
}

var _ Querier = (*Queries)(nil)
