// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/task.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Batyr2024/todoGolang/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockinterfaceRepository is a mock of interfaceRepository interface.
type MockinterfaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockinterfaceRepositoryMockRecorder
}

// MockinterfaceRepositoryMockRecorder is the mock recorder for MockinterfaceRepository.
type MockinterfaceRepositoryMockRecorder struct {
	mock *MockinterfaceRepository
}

// NewMockinterfaceRepository creates a new mock instance.
func NewMockinterfaceRepository(ctrl *gomock.Controller) *MockinterfaceRepository {
	mock := &MockinterfaceRepository{ctrl: ctrl}
	mock.recorder = &MockinterfaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinterfaceRepository) EXPECT() *MockinterfaceRepositoryMockRecorder {
	return m.recorder
}

// ChangeCheckedAll mocks base method.
func (m *MockinterfaceRepository) ChangeCheckedAll(ctx context.Context, checked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCheckedAll", ctx, checked)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeCheckedAll indicates an expected call of ChangeCheckedAll.
func (mr *MockinterfaceRepositoryMockRecorder) ChangeCheckedAll(ctx, checked interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCheckedAll", reflect.TypeOf((*MockinterfaceRepository)(nil).ChangeCheckedAll), ctx, checked)
}

// ChangeCheckedByID mocks base method.
func (m *MockinterfaceRepository) ChangeCheckedByID(ctx context.Context, id int, checked bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeCheckedByID", ctx, id, checked)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeCheckedByID indicates an expected call of ChangeCheckedByID.
func (mr *MockinterfaceRepositoryMockRecorder) ChangeCheckedByID(ctx, id, checked interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeCheckedByID", reflect.TypeOf((*MockinterfaceRepository)(nil).ChangeCheckedByID), ctx, id, checked)
}

// ChangeText mocks base method.
func (m *MockinterfaceRepository) ChangeText(ctx context.Context, id int, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeText", ctx, id, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeText indicates an expected call of ChangeText.
func (mr *MockinterfaceRepositoryMockRecorder) ChangeText(ctx, id, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeText", reflect.TypeOf((*MockinterfaceRepository)(nil).ChangeText), ctx, id, text)
}

// Create mocks base method.
func (m *MockinterfaceRepository) Create(ctx context.Context, task domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockinterfaceRepositoryMockRecorder) Create(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockinterfaceRepository)(nil).Create), ctx, task)
}

// DeleteAll mocks base method.
func (m *MockinterfaceRepository) DeleteAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockinterfaceRepositoryMockRecorder) DeleteAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockinterfaceRepository)(nil).DeleteAll), ctx)
}

// DeleteByID mocks base method.
func (m *MockinterfaceRepository) DeleteByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockinterfaceRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockinterfaceRepository)(nil).DeleteByID), ctx, id)
}

// FindAll mocks base method.
func (m *MockinterfaceRepository) FindAll(ctx context.Context) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockinterfaceRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockinterfaceRepository)(nil).FindAll), ctx)
}
